### ISSUE TITLE
AssertionError: expected false to be truthy

### ISSUE THREAD

**Issue by arnaud** [getgauge-examples/gauge-testcafe#2]
Hi @zabil,

First, thank you for this interesting mixture of Gauge+TestCafé.
I'm relying on your implementation to make gauge and TestCafé work together.

It all works good as long as scenarios are passing.
But the issue I'm facing is the following:
As soon as a step is failing, the rest of the scenario fails (which is good, and by design).
But as soon as a step is failing, all next scenarios fail miserably (which is bad and sad, not by design).

Here is an excerpt of what's going on:

> specs/healthcheck.spec:
```md
# healthcheck

## scenario 1

* This step should pass
* This step should pass

## scenario 2

* This step should fail

## scenario 1

* This step should pass
```

> in the terminal:
```bash
$ gauge run specs/check
# healthcheck
  ## scenario 1
 Running tests in:
 - HeadlessChrome 75.0.3758 / Mac OS X 10.14.3

 fixture
 ✔ ✔
  ## scenario 2
 ✘
        Failed Step: This step should fail
        Specification: specs/check/healthcheck.spec:10
        Error Message: [object Object]
        Stacktrace:

  ## scenario 3
{"code":"E53","isTestCafeError":true,"callsite":{"filename":"tests/step_implementation.js","lineNum":163,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"errMsg":"AssertionError: expected false to be truthy"}
 ✘
        Failed Step: This step should pass
        Specification: specs/check/healthcheck.spec:14
        Error Message: [object Object]
        Stacktrace:

 1 passed (9s)
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	3 executed	1 passed	2 failed	0 skipped

Total time taken: 12.569s
```

> tests/step_implementation.js:
```js
step('This step should pass', async () => {
  await _.expect(true).ok()
})
```

> for reference:
```bash
$ testcafe -v
1.1.1

gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
js (2.3.4)
json-report (0.3.0)
screenshot (0.0.1)
```

I'm willing to share more if needed, I kindly appreciate any help on this issue that starts making neurons unlink pair by pair,

**Comment by arnaud** [comment]
I kinda feel that this may be linked to the way the `test.js` file is created in a mono-fixture way?

**Comment by zabil** [comment]
Refer https://github.com/getgauge/gauge/issues/1382

**Comment by NivedhaSenthil** [comment]
This was happening because testcafe fails execution of test whenever an error occurs at any part of the test file. Since we were creating one test file per suite when there was an error in one scenario others too failed with the same error. Updated the example to create test file and runner for each scenario so that they are independent flows.

**Comment by arnaud** [comment]
It works well now; thank you!!
